'use client';

import React from 'react';

const PrivacyPolicy: React.FC = () => {
  return (
    <div className="max-w-7xl mx-auto p-6">
      <h1 className="text-3xl font-bold mb-4">Privacy Policy</h1>
      <p className="mb-6">Effective Date: January 1, 2024</p>

      <p className="mb-6">
        AthenaShield Inc. (“Company”, “we”, “us”, or “our”) respects your privacy. This Privacy Policy explains how we collect, use, store, and protect the personal information you provide when using our platform (“Platform”).
      </p>

      <h2 className="text-2xl font-semibold mb-4">1. Information We Collect</h2>
      <p className="mb-4">We collect the following types of information when you use our Platform:</p>
      <ul className="list-disc pl-6 mb-6">
        <li><strong>Business Information:</strong> Company name, website, industry, contact details.</li>
        <li><strong>Account Information:</strong> Name, email address, and password.</li>
        <li><strong>Usage Data:</strong> Interactions with the Platform, IP address, browser type, device information, and timestamps.</li>
        <li><strong>AI Model Inputs:</strong> Data entered to analyze emails or generate insights.</li>
      </ul>

      <h2 className="text-2xl font-semibold mb-4">2. How We Use Your Information</h2>
      <p className="mb-4">We use the information we collect to:</p>
      <ul className="list-disc pl-6 mb-6">
        <li>Provide, operate, and improve our email security tools and AI services.</li>
        <li>Respond to your inquiries or support requests.</li>
        <li>Send updates about features, security alerts, or offers (if you opt-in).</li>
        <li>Detect abuse, threats, or suspicious behavior.</li>
        <li>Comply with legal and regulatory obligations.</li>
      </ul>

      <h2 className="text-2xl font-semibold mb-4">3. Data Sharing and Disclosure</h2>
      <p className="mb-4">We do not sell your personal data. We may share information with:</p>
      <ul className="list-disc pl-6 mb-6">
        <li>Trusted third-party service providers (e.g., hosting, analytics, support).</li>
        <li>Law enforcement or authorities when required by law or security threats.</li>
      </ul>

      <h2 className="text-2xl font-semibold mb-4">4. Data Retention</h2>
      <p className="mb-6">
        We retain your information only as long as needed for the purposes outlined in this Policy, unless a longer retention period is legally required.
      </p>

      <h2 className="text-2xl font-semibold mb-4">5. Security</h2>
      <p className="mb-6">
        We implement industry-standard technical and organizational measures to protect your data. However, no digital system is completely secure, and we cannot guarantee absolute protection.
      </p>

      <h2 className="text-2xl font-semibold mb-4">6. AI-Generated Content and Data Use</h2>
      <p className="mb-6">
        Any insights or content generated by AthenaShield&apos;s AI are based on your inputs and email content. You are responsible for reviewing outputs before taking action. We do not share your email content with third parties without consent.
      </p>

      <h2 className="text-2xl font-semibold mb-4">7. International Users</h2>
      <p className="mb-6">
        AthenaShield is based in Canada. If you use the Platform from outside Canada, you consent to your data being processed and stored in Canada under Canadian data protection laws.
      </p>

      <h2 className="text-2xl font-semibold mb-4">8. Your Rights</h2>
      <p className="mb-6">
        Depending on your jurisdiction, you may have rights to access, correct, delete, or restrict the processing of your data. To exercise your rights, please contact us at the email below.
      </p>

      <h2 className="text-2xl font-semibold mb-4">9. Changes to This Privacy Policy</h2>
      <p className="mb-6">
        We may update this Privacy Policy periodically. If changes are material, we will notify you through the Platform or via email. Continued use of the Platform means you accept the revised policy.
      </p>

      <h2 className="text-2xl font-semibold mb-4">10. Contact Us</h2>
      <p className="mb-6">
        If you have any questions or concerns about this Privacy Policy, contact us at:{' '}
        <a href="mailto:hello@athenashield.com" className="text-cyan-700 underline">
          hello@athenashield.com
        </a>
      </p>
    </div>
  );
};

export default PrivacyPolicy;
